#!/bin/bash

# API endpoint
API_BASE_URL="http://localhost:8000"

# Comprehensive sample texts
topic_texts=(
"The quick brown fox jumps over the lazy dog represents one of the most famous pangrams in the English language, containing every letter of the alphabet at least once. Pangrams have been used for centuries to test typewriters, typefaces, and printing presses. The specific phrase 'The quick brown fox jumps over the lazy dog' became popular in the late 19th century during the typewriter era. It was designed to help users test their typing skills and ensure all keys were functioning properly. Beyond its practical applications, this pangram has become a cultural touchstone, appearing in countless books, movies, and advertisements. The phrase demonstrates how 43 characters can encapsulate the entire English alphabet, making it an efficient tool for linguistic testing and demonstration.

Pangrams serve important functions in typography and printing. They allow designers to see how different fonts render all letters together, helping identify spacing issues, kerning problems, and overall readability. The 'quick brown fox' pangram is particularly effective because it uses common, everyday words that flow naturally, unlike more contrived pangrams. This natural flow makes it easier to read and type repeatedly. In the digital age, pangrams continue to be valuable for testing input methods, autocorrect algorithms, and text rendering engines. They help ensure that software can handle the full range of characters in a language. The enduring popularity of this particular pangram speaks to its elegant simplicity and practical utility."

"Machine learning is transforming the world by revolutionizing how computers learn and make decisions without explicit programming. This subset of artificial intelligence enables systems to automatically learn and improve from experience, identifying patterns in data that would be impossible for humans to detect manually. From recommendation systems on streaming platforms to autonomous vehicles navigating city streets, machine learning algorithms power countless applications that shape our daily lives. The field has evolved rapidly since its inception in the 1950s, with breakthroughs in neural networks, deep learning, and computational power enabling unprecedented capabilities.

The impact of machine learning spans virtually every industry. In healthcare, ML algorithms analyze medical images to detect cancer earlier than human doctors. In finance, they detect fraudulent transactions in real-time and assess credit risk more accurately. Transportation companies use ML for route optimization and predictive maintenance. Retailers leverage it for personalized shopping experiences and inventory management. Even creative fields like music and art generation are being transformed by ML models. As the technology matures, ethical considerations around bias, privacy, and job displacement become increasingly important. The future of machine learning promises even more transformative applications, from climate modeling to drug discovery, potentially solving some of humanity's greatest challenges."

"FastAPI is a modern web framework for building APIs that combines high performance with developer-friendly features. Built on Starlette and Pydantic, it offers automatic API documentation generation, data validation, and type hints support that make API development significantly faster and more reliable. Unlike traditional frameworks, FastAPI leverages Python's type annotations to provide runtime data validation and automatic OpenAPI/Swagger documentation. This approach eliminates many common API development pitfalls while maintaining excellent performance comparable to Node.js and Go frameworks.

The framework's async/await support enables handling thousands of concurrent requests efficiently, making it ideal for high-traffic applications. FastAPI's dependency injection system simplifies code organization and testing. Built-in security features include OAuth2, JWT tokens, and API key authentication. The automatic API documentation provides interactive interfaces for testing endpoints without additional tools. FastAPI's growing ecosystem includes tools for database integration, background task processing, and deployment. Its modern Python approach appeals to developers who want to leverage the latest language features while building robust, scalable APIs. The framework's emphasis on developer experience and performance makes it a compelling choice for both startups and enterprise applications."

"Vector databases enable efficient similarity search by storing and retrieving high-dimensional vectors that represent complex data like text, images, and audio. Unlike traditional databases that use exact matching, vector databases use mathematical similarity measures to find related items. This capability is crucial for modern AI applications, enabling semantic search, recommendation systems, and content discovery. Vector databases like Qdrant, Pinecone, and Weaviate have emerged to handle the unique requirements of vector data, including high-dimensional indexing and fast approximate nearest neighbor search.

The technology behind vector databases combines advanced indexing algorithms with machine learning embeddings. When data is stored, it's first converted into vectors using models like word embeddings or image encoders. These vectors capture semantic meaning rather than just keywords. Search queries are similarly vectorized and compared using metrics like cosine similarity or Euclidean distance. Approximate nearest neighbor algorithms enable sub-second search through millions of vectors. Vector databases support operations like filtering, aggregation, and real-time updates. They integrate with popular AI frameworks and support various distance metrics. As AI applications proliferate, vector databases are becoming essential infrastructure for modern software systems."

"Python is a versatile programming language that has become the lingua franca of modern software development. Created by Guido van Rossum in 1991, Python emphasizes code readability and simplicity, making it accessible to beginners while powerful enough for experts. Its extensive standard library and third-party ecosystem cover everything from web development to scientific computing. Python's philosophy of 'batteries included' means developers can accomplish complex tasks with minimal code. The language's dynamic typing and interpreted nature enable rapid prototyping and iterative development.

Python's versatility spans multiple domains. In web development, frameworks like Django and Flask power everything from simple blogs to complex enterprise applications. Scientific computing relies on NumPy, SciPy, and pandas for data analysis and visualization. Machine learning practitioners use scikit-learn, TensorFlow, and PyTorch for AI development. Automation and scripting tasks benefit from Python's clear syntax and extensive libraries. The language's cross-platform nature ensures code runs consistently across operating systems. Python's community-driven development model, with PEPs (Python Enhancement Proposals) guiding evolution, ensures the language remains relevant and innovative. Its adoption by major tech companies and educational institutions cements its status as a foundational programming language."

"Natural language processing helps computers understand text by bridging the gap between human language and machine computation. This field of AI focuses on enabling computers to comprehend, interpret, and generate human language. From voice assistants like Siri and Alexa to automated translation services, NLP powers many of the language-related technologies we use daily. The field combines linguistics, computer science, and machine learning to tackle challenges like syntactic analysis, semantic understanding, and contextual interpretation.

Modern NLP systems use transformer architectures and large language models trained on vast amounts of text data. These models can perform tasks like sentiment analysis, named entity recognition, machine translation, and text summarization. The technology has evolved from rule-based systems to statistical models to today's neural network approaches. Challenges include handling ambiguity, context-dependence, and cultural nuances in language. Applications range from customer service chatbots to content moderation systems. As NLP capabilities advance, ethical considerations around bias, privacy, and misinformation become increasingly important. The field continues to push boundaries, with models like GPT demonstrating remarkable language generation capabilities."

"Redis is an in-memory data structure store that serves as a high-performance database, cache, and message broker. Originally created by Salvatore Sanfilippo in 2009, Redis stores data in memory for lightning-fast access while providing optional persistence to disk. Its support for various data structures like strings, hashes, lists, sets, and sorted sets makes it incredibly versatile. Redis can function as a cache, session store, real-time analytics engine, or message queue. Its single-threaded architecture ensures predictable performance and simplifies concurrency management.

Redis's speed and simplicity have made it a cornerstone of modern application architectures. It powers caching layers that reduce database load and improve response times. As a message broker, it enables decoupled microservices communication through pub/sub patterns. Redis clusters provide high availability and horizontal scaling. The database supports Lua scripting for complex operations and transactions. Its rich ecosystem includes clients for virtually every programming language. Redis's design philosophy emphasizes speed, simplicity, and versatility, making it an essential tool for developers building high-performance applications. The project's active community and commercial support ensure its continued evolution and reliability."

"PostgreSQL is a powerful relational database that combines advanced features with open-source reliability. Originally developed at UC Berkeley in the 1980s, PostgreSQL has evolved into one of the most advanced open-source databases available. Its support for SQL standards, ACID transactions, and advanced data types makes it suitable for everything from small applications to large enterprise systems. PostgreSQL's extensibility allows developers to add custom data types, operators, and functions. Features like JSON support, full-text search, and spatial data capabilities address modern application needs.

The database's robustness and feature set make it a popular choice for demanding applications. It supports complex queries, indexing strategies, and concurrent access patterns. PostgreSQL's extensibility through custom functions and data types enables specialized use cases. The database includes advanced features like table inheritance, window functions, and common table expressions. Its support for multiple programming languages and frameworks simplifies integration. The active community and commercial support options ensure PostgreSQL remains a reliable, feature-rich database solution. Organizations worldwide trust PostgreSQL for mission-critical applications requiring data integrity and performance."

"Docker containers simplify deployment by packaging applications with their dependencies into standardized units. This containerization technology, introduced by Docker Inc. in 2013, revolutionized software deployment by solving the 'works on my machine' problem. Containers package code, runtime, libraries, and system tools into isolated environments that run consistently across different platforms. Unlike virtual machines, containers share the host system's kernel, making them lightweight and efficient. Docker's layered filesystem and copy-on-write mechanism optimize storage and startup times.

The technology has transformed DevOps practices and microservices architectures. Containers enable immutable deployments, where applications are packaged once and deployed consistently across environments. Orchestration tools like Kubernetes manage container lifecycles at scale. Docker's ecosystem includes registries for sharing containers and development tools for building and testing. The platform supports multi-stage builds for optimized production images. Security features like image scanning and runtime protection enhance container safety. Docker's impact extends beyond deployment to influence how teams develop, test, and deliver software. The containerization paradigm has become fundamental to cloud-native application development."

"Sentence transformers create text embeddings by converting sentences into dense vector representations that capture semantic meaning. Developed by researchers at UKP Lab, sentence transformers use transformer architectures like BERT and RoBERTa to generate fixed-length vectors from variable-length text. These embeddings enable semantic similarity comparisons, clustering, and information retrieval tasks. Unlike word embeddings, sentence embeddings represent entire sentences or paragraphs as single vectors. The models are trained on large datasets using contrastive learning objectives that bring similar sentences closer in vector space.

The technology powers applications like semantic search, text clustering, and paraphrase detection. Sentence transformers support multiple languages and domains, with models fine-tuned for specific tasks. The embeddings can be used with various similarity metrics like cosine similarity or dot product. Integration with vector databases enables efficient similarity search at scale. The field continues to evolve with larger models and better training techniques. Sentence transformers have become essential tools for natural language processing applications requiring semantic understanding. Their ability to capture nuanced meaning makes them valuable for tasks ranging from document similarity to recommendation systems."

"Basketball, invented by Dr. James Naismith in 1891, has evolved from a simple indoor game using peach baskets to a global phenomenon watched by billions. The sport began as a way to keep athletes active during harsh Canadian winters, with 13 basic rules scribbled on a piece of paper. Early games featured nine players per team and running with the ball was allowed. The introduction of the dribble in 1897 revolutionized gameplay, making it more dynamic. The NBA, founded in 1946, transformed basketball into a professional spectacle. Iconic players like Michael Jordan, LeBron James, and Kobe Bryant have elevated the sport to cultural status. Modern basketball features advanced analytics, three-point shooting emphasis, and global expansion with leagues in Europe, Asia, and Australia. The game continues to innovate with new rules like the shot clock and hand-checking restrictions, ensuring it remains fast-paced and exciting for future generations.

The evolution of basketball strategy has been remarkable. From the early days of slow-paced, inside-dominated play, the game has transformed into a fast-break, perimeter-oriented spectacle. The introduction of the three-point line in 1979 changed how the game is played, rewarding long-range shooting and spacing. Analytics have revolutionized coaching, with teams using data to optimize player rotations, shot selection, and defensive schemes. The rise of positionless basketball, where players can play multiple roles, has created more versatile athletes. International growth has brought diverse playing styles, with European efficiency meeting American athleticism. The WNBA has provided a platform for women's basketball excellence, with stars like Sue Bird, Lauren Jackson, and Rebecca Lobo paving the way for current superstars like Elena Delle Donne and Breanna Stewart."

"The FIFA World Cup, held every four years since 1930, represents the pinnacle of international soccer achievement. What began as a tournament for 13 teams in Uruguay has grown to include 32 nations competing for global supremacy. Brazil leads with five titles, followed by Germany and Italy with four each. The tournament showcases incredible athleticism, tactical brilliance, and moments of pure magic. Legendary players like Pelé, Diego Maradona, and Lionel Messi have left indelible marks on the competition. The 2018 World Cup in Russia drew over 3 billion viewers, making it the most watched sporting event on Earth. Beyond the glory, the World Cup promotes cultural exchange and national pride. Controversies like the 1986 'Hand of God' goal and the 2022 Qatar hosting debates have sparked global conversations. Despite challenges, the World Cup continues to unite fans worldwide in celebration of the beautiful game.

The tournament's format has evolved significantly over the years. Originally featuring just 13 teams in a single-elimination format, it now includes 32 nations competing in a group stage followed by knockout rounds. The introduction of the group stage in 1950 created more matches and increased revenue opportunities. Technology has transformed the game, with VAR (Video Assistant Referee) introduced in 2018 to improve decision-making accuracy. The World Cup has driven infrastructure development in host countries, from stadium construction to transportation improvements. Economic impact is enormous, with billions in revenue from broadcasting rights, sponsorships, and tourism. The tournament has inspired countless youth programs worldwide, developing the next generation of talent. Despite commercialization concerns, the World Cup remains a celebration of human athletic achievement and cultural diversity."

"The four Grand Slam tournaments - Wimbledon, the US Open, the French Open, and the Australian Open - represent tennis's most prestigious competitions. Each event has unique characteristics that challenge players differently. Wimbledon, played on grass at the All England Club, demands serve-and-volley mastery and quick reflexes. The French Open's clay courts at Roland Garros requires endurance and topspin expertise. The US Open's hard courts in Flushing Meadows favors powerful serving and aggressive baseline play. The Australian Open's fast hard courts reward consistency and athleticism. Legends like Roger Federer, Serena Williams, and Rafael Nadal have dominated these events, with Nadal's 14 French Open titles setting a remarkable record. The Grand Slams test players' physical and mental limits over two weeks of intense competition. Emerging stars like Carlos Alcaraz and Iga Świątek continue the tradition of excellence. These tournaments not only crown champions but also shape the future of tennis through innovation and tradition.

The Grand Slam tournaments have evolved dramatically since their inception. Wimbledon, established in 1877, was the first and remains the most prestigious. The French Open joined in 1925, followed by the Australian Open in 1905 (though it became a major in the 1980s), and the US Open in 1881. Court surfaces have remained consistent, each testing different skills. Grass rewards serve-and-volley and quick movement. Clay demands patience, endurance, and topspin mastery. Hard courts favor power and consistency. The tournaments have driven technological innovation, from wooden rackets to carbon fiber, from white balls to optic yellow. Prize money has increased exponentially, from modest sums to millions of dollars. The events have become global spectacles, broadcast to billions worldwide. They continue to maintain traditions like Wimbledon's all-white dress code and strict etiquette while embracing modern technology."

"American football, born from rugby and football traditions, has become America's most popular sport with a passionate fanbase and massive economic impact. The NFL, founded in 1920, oversees a league of 32 teams competing in a 17-week regular season followed by playoffs and the Super Bowl. The game combines strategic complexity with physical athleticism, requiring players to master intricate playbooks while performing at peak physical condition. Quarterbacks like Tom Brady, Peyton Manning, and Patrick Mahomes have revolutionized the position with their decision-making and accuracy. The Super Bowl has become a cultural phenomenon, watched by over 100 million viewers annually and featuring elaborate halftime shows. Fantasy football engages millions of fans in season-long strategy games. The sport generates billions in revenue through television contracts, merchandise, and ticket sales. Despite concussion concerns and player safety debates, the NFL continues to innovate with rule changes and technology to protect athletes while maintaining the game's excitement."

"Italian cuisine represents a perfect marriage of simplicity, quality ingredients, and regional diversity. At its heart lies pasta, with over 600 varieties from spaghetti to tortellini, each telling a story of local traditions. Fresh tomatoes, olive oil, garlic, and herbs form the foundation of many dishes. Northern Italy offers rich risottos and polenta, while the south features spicy arrabbiata and fresh seafood. Pizza, born in Naples, has evolved from a simple flatbread to a global phenomenon with countless variations. Traditional recipes like osso buco, tiramisu, and gelato showcase Italy's culinary heritage. The Mediterranean diet, centered on Italian eating habits, has been recognized by UNESCO as an intangible cultural heritage. Modern Italian chefs continue to innovate while respecting traditions. Family meals remain central to Italian culture, with food bringing people together for hours of conversation and laughter. Italian cuisine teaches us that great food doesn't need complexity - just passion and the best ingredients.

The regional diversity of Italian cuisine is remarkable. Piedmont offers the famous white truffle and Barolo wine. Lombardy features risotto alla Milanese and ossobuco. Veneto is known for polenta, baccalà, and Prosecco. Emilia-Romagna boasts Parma ham, Parmigiano-Reggiano, and balsamic vinegar. Tuscany features simple, rustic dishes like ribollita and bistecca alla Fiorentina. Sicily offers couscous, caponata, and pistachio desserts. Sardinia provides bottarga and myrtle liqueur. Each region has developed its cuisine based on local ingredients, climate, and history. This diversity creates a culinary map of Italy, where traveling becomes a gastronomic journey. The Slow Food movement, born in Piedmont, celebrates this regional heritage and promotes sustainable, quality food production worldwide."

"Asian fusion cooking represents the exciting intersection of diverse culinary traditions, blending Eastern flavors with Western techniques. This innovative approach combines Japanese precision, Chinese wok mastery, Thai aromatic spices, and Indian complex curries. Modern fusion dishes might feature sushi rolls with unexpected fillings, Korean barbecue tacos, or Vietnamese banh mi with international twists. Chefs like Roy Choi and David Chang have popularized this movement, creating accessible yet sophisticated cuisine. Fusion cooking respects traditional ingredients while encouraging creativity. Techniques like sous-vide meet with traditional steaming, creating new textures and flavors. The movement promotes cultural exchange and breaks down culinary barriers. Fusion restaurants often feature shared plates, encouraging exploration of different flavor profiles. This approach has democratized Asian cuisine, making complex flavors accessible to broader audiences. As globalization continues, Asian fusion cooking evolves, reflecting our interconnected world.

The fusion movement has revolutionized how we think about Asian cuisine. Korean-Mexican fusion combines kimchi with tacos, creating explosive flavor combinations. Japanese-French fusion might feature sushi with foie gras or miso-glazed sea bass. Thai-Italian fusion could combine curry with pasta or pad thai elements with pizza. Indian-American fusion has given us butter chicken pizza and curry fries. The key to successful fusion is balance - respecting the integrity of each culinary tradition while finding harmonious combinations. Fusion has made Asian ingredients and techniques accessible to Western audiences, demystifying complex cuisines. It has also influenced traditional Asian restaurants to experiment with new presentations and flavor combinations. As immigration patterns change and global communication improves, fusion cooking continues to evolve, creating new culinary possibilities."

"Healthy eating goes beyond calorie counting to encompass nutrient density, gut health, and sustainable food choices. Micronutrients like vitamins, minerals, and antioxidants play crucial roles in preventing chronic diseases. The gut microbiome, influenced by fiber-rich foods, affects immunity and mental health. Plant-based diets rich in vegetables, fruits, whole grains, and legumes provide optimal nutrition. Omega-3 fatty acids from fish, nuts, and seeds support brain and heart health. Understanding glycemic index helps manage blood sugar levels. Hydration and mindful eating practices enhance nutrient absorption. Sustainable food choices consider environmental impact and ethical farming. Personalized nutrition recognizes individual genetic and lifestyle factors. Modern research emphasizes food synergy - how nutrients work together for maximum benefit. Healthy eating isn't restrictive but celebratory, focusing on nourishing the body while enjoying diverse, flavorful foods.

The Mediterranean diet, inspired by traditional eating patterns in Greece, Italy, and Spain, has been extensively studied for its health benefits. Rich in olive oil, fish, fruits, vegetables, and whole grains, it emphasizes plant-based foods over processed meats and sugars. Studies show it reduces heart disease risk, improves cognitive function, and supports healthy aging. The diet includes moderate wine consumption, particularly red wine, and emphasizes social eating with family and friends. Similar benefits come from traditional Japanese, Okinawan, and Nordic diets, all emphasizing whole foods and balanced nutrition. Modern research into intermittent fasting, ketogenic diets, and plant-based eating continues to expand our understanding of optimal nutrition. The key is finding sustainable eating patterns that nourish both body and soul."

"Molecular gastronomy represents the scientific exploration of cooking, where chefs become culinary scientists pushing the boundaries of flavor, texture, and presentation. Pioneered by chefs like Ferran Adrià at elBulli and Heston Blumenthal at The Fat Duck, this movement applies scientific principles to create extraordinary dining experiences. Techniques include spherification, foams, gels, and flavor encapsulation. Molecular gastronomy challenges traditional notions of what food should be, creating edible art that engages multiple senses. It has influenced both fine dining and home cooking, introducing new techniques and ingredients. While controversial for its complexity and cost, it has advanced our understanding of flavor chemistry and sensory perception. The movement continues to evolve, with chefs exploring sustainable sourcing and nutritional enhancement through scientific methods. Molecular gastronomy bridges art, science, and cuisine in unprecedented ways."

"The Olympic Games, both Summer and Winter, represent the pinnacle of international athletic achievement and cultural celebration. Originating in ancient Greece in 776 BC, the modern Olympics began in 1896 with the Athens games. The Summer Olympics feature 33 sports and over 300 events, while the Winter Olympics include skiing, skating, and snowboarding competitions. The games bring together athletes from over 200 nations in a celebration of human potential and international cooperation. Iconic moments like Jesse Owens' 1936 victories, Nadia Comaneci's 1976 gymnastics scores, and Usain Bolt's record-breaking sprints have become legendary. The Olympics have evolved to include women's events, Paralympic competitions, and greater diversity in participation. They drive technological innovation, from athletic equipment to broadcast technology. Economic impact is enormous, with host cities investing billions in infrastructure. Despite controversies over costs, doping, and politics, the Olympics continue to inspire youth worldwide and promote peace through sport."

"Golf, often called 'a good walk spoiled,' has evolved from a simple Scottish pastime to a global sport with immense cultural and economic impact. The game originated in 15th-century Scotland, spreading worldwide through British colonial influence. The modern game features 18 holes played with clubs and a ball, requiring precision, strategy, and mental focus. Major championships like the Masters, PGA Championship, US Open, and British Open attract millions of viewers. Legends like Jack Nicklaus, Tiger Woods, and Rory McIlroy have shaped the sport's history. Golf courses range from links-style coastal layouts to desert and mountain designs, each presenting unique challenges. The sport has embraced technology with advanced club design and swing analysis tools. Despite perceptions of exclusivity, golf has become more accessible with public courses and junior programs. It teaches patience, perseverance, and sportsmanship. The Ryder Cup and Presidents Cup create international rivalries. Golf continues to evolve while maintaining its traditional charm and strategic depth."
)

# Function to add text via API
add_text_via_api() {
    local text="$1"
    response=$(python3 -c "
import sys
import requests
text = sys.argv[1]
response = requests.post('$API_BASE_URL/add_text', json={'text': text})
if response.status_code == 200:
    data = response.json()
    print(f'Added: {text[:30]}... (ID: {data[\"id\"]})')
else:
    print(f'Failed: {response.status_code} {response.text}')
" "$text")
    echo "$response"
}

# Delete all existing texts
echo "Deleting all existing texts..."
response=$(python3 -c "
import requests
response = requests.delete('$API_BASE_URL/delete_all_texts')
if response.status_code == 200:
    print('All texts deleted successfully')
else:
    print(f'Failed to delete: {response.status_code} {response.text}')
")

# Add topic texts
echo "Adding food and sports topic texts..."
for text in "${topic_texts[@]}"; do
    add_text_via_api "$text"
done

echo "Sample data addition complete!"