# Generated by the protocol buffer compiler.  DO NOT EDIT!

import grpc

import audio_pb2 as audio__pb2


class AudioServiceStub(object):
    def __init__(self, channel):
        self.GenerateAudioFromText = channel.unary_unary(
            "/AudioService/GenerateAudioFromText",
            request_serializer=audio__pb2.GenerateAudioFromTextRequest.SerializeToString,
            response_deserializer=audio__pb2.GenerateAudioResponse.FromString,
        )
        self.GenerateAudioFromId = channel.unary_unary(
            "/AudioService/GenerateAudioFromId",
            request_serializer=audio__pb2.GenerateAudioFromIdRequest.SerializeToString,
            response_deserializer=audio__pb2.GenerateAudioResponse.FromString,
        )


class AudioServiceServicer(object):
    def GenerateAudioFromText(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateAudioFromId(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GenerateAudioFromText": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateAudioFromText,
            request_deserializer=audio__pb2.GenerateAudioFromTextRequest.FromString,
            response_serializer=audio__pb2.GenerateAudioResponse.SerializeToString,
        ),
        "GenerateAudioFromId": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateAudioFromId,
            request_deserializer=audio__pb2.GenerateAudioFromIdRequest.FromString,
            response_serializer=audio__pb2.GenerateAudioResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "AudioService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
