# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\"]\n\x1cGenerateAudioFromTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\r\n\x05voice\x18\x04 \x01(\t\"Y\n\x1aGenerateAudioFromIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\r\n\x05voice\x18\x04 \x01(\t\"P\n\x15GenerateAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x32\xaa\x01\n\x0c\x41udioService\x12N\n\x15GenerateAudioFromText\x12\x1d.GenerateAudioFromTextRequest\x1a\x16.GenerateAudioResponse\x12J\n\x13GenerateAudioFromId\x12\x1b.GenerateAudioFromIdRequest\x1a\x16.GenerateAudioResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERATEAUDIOFROMTEXTREQUEST._serialized_start=15
  _GENERATEAUDIOFROMTEXTREQUEST._serialized_end=108
  _GENERATEAUDIOFROMIDREQUEST._serialized_start=110
  _GENERATEAUDIOFROMIDREQUEST._serialized_end=199
  _GENERATEAUDIORESPONSE._serialized_start=201
  _GENERATEAUDIORESPONSE._serialized_end=281
  _AUDIOSERVICE._serialized_start=284
  _AUDIOSERVICE._serialized_end=454
# @@protoc_insertion_point(module_scope)
