# Generated by the protocol buffer compiler.  DO NOT EDIT!

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))

from google.protobuf import descriptor as _descriptor

from google.protobuf import message as _message

from google.protobuf import reflection as _reflection

from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name="search.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=_b(
        '\n\x0csearch.proto"\'\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t"*\n\x0eSearchResponse\x12\x0e\n\x02ids\x18\x01 \x03(\t2^\n\rSearchService\x12M\n\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponse"\x00\x62\x06proto3'
    ),
)

_SEARCHREQUEST = _descriptor.Descriptor(
    name="SearchRequest",
    full_name="SearchRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="query",
            full_name="SearchRequest.query",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=14,
    serialized_end=47,
)

_SEARCHRESPONSE = _descriptor.Descriptor(
    name="SearchResponse",
    full_name="SearchResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="ids",
            full_name="SearchResponse.ids",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=49,
    serialized_end=85,
)

_SEARCHSERVICE = _descriptor.ServiceDescriptor(
    name="SearchService",
    full_name="SearchService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=87,
    serialized_end=152,
    methods=[
        _descriptor.MethodDescriptor(
            name="Search",
            full_name="SearchService.Search",
            index=0,
            containing_service=None,
            input_type=_SEARCHREQUEST,
            output_type=_SEARCHRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)

DESCRIPTOR.message_types_by_name["SearchRequest"] = _SEARCHREQUEST

DESCRIPTOR.message_types_by_name["SearchResponse"] = _SEARCHRESPONSE

_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchRequest = _reflection.GeneratedProtocolMessageType(
    "SearchRequest",
    (_message.Message,),
    {"DESCRIPTOR": _SEARCHREQUEST, "__module__": "search_pb2"},
)

_sym_db.RegisterMessage(SearchRequest)

SearchResponse = _reflection.GeneratedProtocolMessageType(
    "SearchResponse",
    (_message.Message,),
    {"DESCRIPTOR": _SEARCHRESPONSE, "__module__": "search_pb2"},
)

_sym_db.RegisterMessage(SearchResponse)
