# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcribe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10transcribe.proto\"d\n\x16TranscribeAudioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x14\n\x0cmax_duration\x18\x04 \x01(\x05\"o\n\x17TranscribeAudioResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x19\n\x11\x64\x65tected_language\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x17\n\x0fprocessing_time\x18\x04 \x01(\x02\x32Z\n\x12TranscriberService\x12\x44\n\x0fTranscribeAudio\x12\x17.TranscribeAudioRequest\x1a\x18.TranscribeAudioResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcribe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSCRIBEAUDIOREQUEST._serialized_start=20
  _TRANSCRIBEAUDIOREQUEST._serialized_end=120
  _TRANSCRIBEAUDIORESPONSE._serialized_start=122
  _TRANSCRIBEAUDIORESPONSE._serialized_end=233
  _TRANSCRIBERSERVICE._serialized_start=235
  _TRANSCRIBERSERVICE._serialized_end=325
# @@protoc_insertion_point(module_scope)
