# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0csearch.proto"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t"\x1d\n\x0eSearchResponse\x12\x0b\n\x03ids\x18\x01 \x03(\t2:\n\rSearchService\x12)\n\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "search_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SEARCHREQUEST"]._serialized_start = 16
    _globals["_SEARCHREQUEST"]._serialized_end = 46
    _globals["_SEARCHRESPONSE"]._serialized_start = 48
    _globals["_SEARCHRESPONSE"]._serialized_end = 77
    _globals["_SEARCHSERVICE"]._serialized_start = 79
    _globals["_SEARCHSERVICE"]._serialized_end = 137
# @@protoc_insertion_point(module_scope)
