# Generated by the protocol buffer compiler.  DO NOT EDIT!

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))

from google.protobuf import descriptor as _descriptor

from google.protobuf import message as _message

from google.protobuf import reflection as _reflection

from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name="audio.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=_b(
        '\n\x0b\x61udio.proto"N\n\x1dGenerateAudioFromTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06format\x18\x02 \x01(\t"I\n\x1aGenerateAudioFromIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06format\x18\x02 \x01(\t"I\n\x15GenerateAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0e\n\x06format\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x32\x8a\x01\n\x0bAudioService\x12I\n\x15GenerateAudioFromText\x12\x1eGenerateAudioFromTextRequest\x1a\x16GenerateAudioResponse\x12\x44\n\x12GenerateAudioFromId\x12\x1bGenerateAudioFromIdRequest\x1a\x16GenerateAudioResponse\x62\x06proto3'
    ),
)

_GENERATEAUDIOFROMTEXTREQUEST = _descriptor.Descriptor(
    name="GenerateAudioFromTextRequest",
    full_name="GenerateAudioFromTextRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="text",
            full_name="GenerateAudioFromTextRequest.text",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="format",
            full_name="GenerateAudioFromTextRequest.format",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=14,
    serialized_end=80,
)

_GENERATEAUDIOFROMIDREQUEST = _descriptor.Descriptor(
    name="GenerateAudioFromIdRequest",
    full_name="GenerateAudioFromIdRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="GenerateAudioFromIdRequest.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="format",
            full_name="GenerateAudioFromIdRequest.format",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=82,
    serialized_end=145,
)

_GENERATEAUDIORESPONSE = _descriptor.Descriptor(
    name="GenerateAudioResponse",
    full_name="GenerateAudioResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="audio_data",
            full_name="GenerateAudioResponse.audio_data",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="format",
            full_name="GenerateAudioResponse.format",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="sample_rate",
            full_name="GenerateAudioResponse.sample_rate",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=147,
    serialized_end=210,
)

DESCRIPTOR.message_types_by_name["GenerateAudioFromTextRequest"] = (
    _GENERATEAUDIOFROMTEXTREQUEST
)

DESCRIPTOR.message_types_by_name["GenerateAudioFromIdRequest"] = (
    _GENERATEAUDIOFROMIDREQUEST
)

DESCRIPTOR.message_types_by_name["GenerateAudioResponse"] = _GENERATEAUDIORESPONSE

_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenerateAudioFromTextRequest = _reflection.GeneratedProtocolMessageType(
    "GenerateAudioFromTextRequest",
    (_message.Message,),
    {"DESCRIPTOR": _GENERATEAUDIOFROMTEXTREQUEST, "__module__": "audio_pb2"},
)

_sym_db.RegisterMessage(GenerateAudioFromTextRequest)

GenerateAudioFromIdRequest = _reflection.GeneratedProtocolMessageType(
    "GenerateAudioFromIdRequest",
    (_message.Message,),
    {"DESCRIPTOR": _GENERATEAUDIOFROMIDREQUEST, "__module__": "audio_pb2"},
)

_sym_db.RegisterMessage(GenerateAudioFromIdRequest)

GenerateAudioResponse = _reflection.GeneratedProtocolMessageType(
    "GenerateAudioResponse",
    (_message.Message,),
    {"DESCRIPTOR": _GENERATEAUDIORESPONSE, "__module__": "audio_pb2"},
)

_sym_db.RegisterMessage(GenerateAudioResponse)
